## Homework 2

This homework covers the material in Lessons 3 & 4.  It is due **Thurday, June 15**.  Please submit your **answers as a PDF**.

1\. Modify the LU method (without pivoting) to work **in-place**.  That is, it should not allocate any new memory for L or U, but instead overwrite A.

In [8]:
def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
            # print(f'LU:\n{L}\n{U}')
    return L, U

def LU_inplace(A):
    m, n = A.shape
    for k in range(n-1):
        for j in range(k+1,n):
            Lt = A[j,k]/A[k,k]
            A[j,k:n] -= Lt * A[k,k:n]
            A[j,k] = Lt
            # print(f'LU_inplace:\n{A}')
    return A

import numpy as np

A = np.array([[1,2,3],
              [2,3,8],
              [4,7,6]], float)

LU(A), LU_inplace(A)

((array([[1., 0., 0.],
         [2., 1., 0.],
         [4., 1., 1.]]),
  array([[ 1.,  2.,  3.],
         [ 0., -1.,  2.],
         [ 0.,  0., -8.]])),
 array([[ 1.,  2.,  3.],
        [ 2., -1.,  2.],
        [ 4.,  1., -8.]]))

2\. Modify our LU method from class to add pivoting, as described in the lesson.  *Hint: the swap method below will be useful* 

In [23]:
def swap(a,b):
    temp = np.copy(a)
    a[:] = b
    b[:] = temp

def LU_pivot(A):
    m, n = A.shape
    L = np.zeros([n,n])
    U = np.copy(A)
    P = np.eye(n)

    print(f'LU:\n{L}\n{U}\n{P}')

    for k in range(n): # procesesing pivot (k,k)

        # swap row to get greatest pivot
        max_r = k 
        for j in range(k+1,n): 
            if U[j,k] > U[max_r,k]:
                max_r = j
        swap(L[k], L[max_r])
        swap(U[k], U[max_r])
        swap(P[k], P[max_r])

        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
        
        L[k,k] = 1.

    return L, U, np.array(P)

A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]],float)
L, U, P = LU_pivot(A)
A, L, U, P

LU:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
LU:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[8. 7. 9. 5.]
 [4. 3. 3. 1.]
 [2. 1. 1. 0.]
 [6. 7. 9. 8.]]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
LU:
[[0.  0.  0.  0. ]
 [0.5 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
[[ 8.   7.   9.   5. ]
 [ 0.  -0.5 -1.5 -1.5]
 [ 2.   1.   1.   0. ]
 [ 6.   7.   9.   8. ]]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
LU:
[[0.   0.   0.   0.  ]
 [0.5  0.   0.   0.  ]
 [0.25 0.   0.   0.  ]
 [0.   0.   0.   0.  ]]
[[ 8.    7.    9.    5.  ]
 [ 0.   -0.5  -1.5  -1.5 ]
 [ 0.   -0.75 -1.25 -1.25]
 [ 6.    7.    9.    8.  ]]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
LU:
[[0.   0.   0.   0.  ]
 [0.5  0.   0.   0.  ]
 [0.25 0.   0.   0.  ]
 [0.75 0.   0.   0.  ]]
[[ 8.    7.    9.    5.  ]


(array([[2., 1., 1., 0.],
        [4., 3., 3., 1.],
        [8., 7., 9., 5.],
        [6., 7., 9., 8.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.75      ,  1.        ,  0.        ,  0.        ],
        [ 0.25      , -0.42857143,  1.        ,  0.        ],
        [ 0.5       , -0.28571429,  3.        ,  1.        ]]),
 array([[ 8.        ,  7.        ,  9.        ,  5.        ],
        [ 0.        ,  1.75      ,  2.25      ,  4.25      ],
        [ 0.        ,  0.        , -0.28571429,  0.57142857],
        [ 0.        ,  0.        ,  0.        , -2.        ]]),
 array([[0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]))

3\. For each of the following sets of dimensions, either
  - give the dimensions of the output of an operation on A and B, **or** 
  - answer *incompatible* if the dimensions are incompatible according to the [numpy rules of broadcasting](https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html).

    a.  A      (2d array):  3 x 3
        B      (1d array):      1

    b.  A      (2d array):      2 x 1
        B      (3d array):  6 x 4 x 2

    c.  A      (2d array):  5 x 4
        B      (1d array):      4

    d.  A      (3d array):  32 x 64 x 8
        B      (3d array):   32 x 1 x 8

    e.  A      (3d array):       64 x 1
        B      (3d array):  32 x 1 x 16

    f.  A      (3d array):  32 x 64 x 2
        B      (3d array):   32 x 1 x 8

a. 3 x 3

b. incompatible

c. 5 x 4

d. 32 x 64 x 8

e. 32 x 64 x 16

f. incompatible

4\. Write how this matrix would be stored in compressed row format:

\begin{pmatrix}
  1 & & & & -2 & -3 \\
  & 3 &  & & & -9 \\
  &  &  & -7 & 4 & \\ 
  -1 & 2 & & 7 & & \\
  -3 & & & 26 & &
 \end{pmatrix}

| Index | Val | RowPtr | Col |
|-------|-----|--------|-----|
| 0     | 1   | 0      | 0   |
| 1     | -2  | 3      | 3   |
| 2     | -3  | 5      | 4   |
| 3     | 3   | 7      | 1   |
| 4     | -9  | 10     | 4   |
| 5     | -7  | 12     | 2   |
| 6     | 4   |        | 3   |
| 7     | -1  |        | 0   |
| 8     | 2   |        | 1   |
| 9     | 7   |        | 2   |
| 10    | -3  |        | 0   |
| 11    | 26  |        | 2   |